### ISSUE TITLE
Typo in orchestration lab

### ISSUE THREAD

**Issue by yogeek** [play-with-docker/play-with-docker.github.io#103]
In the "Docker Orchestration Lab" located here https://training.play-with-docker.com/orchestration-hol/ there is a typo in the main title :

> Docker Orchstration Hands-on Lab

instead of

> Docker Orch**e**stration Hands-on Lab

Do I have to make a PR to correct it ?
Thank you

**Comment by marcosnils** [comment]
@yogeek please, that'd be awesome!.

**Comment by yogeek** [comment]
Closed by #106

**Comment by yogeek** [comment]
@marcosnils Is the master branch automatically deployed on the "https://training.play-with-docker.com/" labs (if so, how long does it take ?) or is it done on a regular basis (and if so, how often ?)

**Comment by marcosnils** [comment]
Changes are deployed automatically. If you check this lab for example (https://training.play-with-docker.com/orchestration-hol/) the title is already fixed per your PR

**Comment by yogeek** [comment]
@marcosnils  In fact, I am still seeing the old page, that's why I asked ;-) (although I tried cleaning the cache and in private navigation to be sure)
Any idea why ?

**Comment by marcosnils** [comment]
Do you still not see the changes? I just checked again from a different device and all of them seem to be there

**Comment by yogeek** [comment]
Just tested from computer and smartphone : same result, I am still seeing the typo...
